version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-vendas
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: vendas_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vendas-network

volumes:
  postgres_data:

networks:
  vendas-network:
    driver: bridge